# Generated by Django 4.0.4 on 2022-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DONE', 'DONE')], default='ACTIVE', max_length=10),
        ),
    ]
