ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_ACTIVE = "ACTIVE"
ORDER_STATUS_DONE = "DONE"

ORDER_STATUSES = [(ORDER_STATUS_PENDING, ORDER_STATUS_PENDING),
                  (ORDER_STATUS_ACTIVE, ORDER_STATUS_ACTIVE),
                  (ORDER_STATUS_DONE, ORDER_STATUS_DONE)]
